config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  resources :images
  
  resources :users do 
  	resources :boards do
  		collection do
  			get :board_selection
  			
  		end
  	end
  end
  post '/boards/update_boards'
  root to: "images#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id
  validates :name, uniqueness: true
  validates :name, presence: true

  has_many :categories
  has_many :images, through: :categories
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  $value = 0
  def index
    @boards = Board.where(user_id: current_user)
  end

  #providing all the boards associated with current user
  def board_selection
    @photo_id = params[:image_id]
    $value = @photo_id
    @boards = Board.where(user_id: current_user)
    @category = Category.new
  end

  #creating a field in database with the image id and tag id in the database
  def update_boards
    selected_board_id = params[:board_id]
    photo_id = params[:image_id]
    message = ""
    #Category is having many to many relationship

    #checking if the board already contains this image or not 
    if Category.find_by(board_id: selected_board_id, image_id: photo_id).present?
      message =  "already"
    else
      cat = Category.new(board_id: selected_board_id, image_id: photo_id)
      if cat.save
        message = "success"
      else
        message = "failed"
      end
    end
    render :json => {message: message}
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
    @board.user_id = current_user.id
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id

    respond_to do |format|
      if @board.save
        format.html { redirect_to user_board_path(current_user.id, @board), notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to user_board_path(current_user.id, @board), notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to user_boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :user_id, :board_id, :image_id)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board_selection.html.erb
<div class = "board_selection_container">
	<%= form_for(@category, :url => update_boards_user_boards_path(current_user.id, @board), :html => { :method => :post } ) do |f| %>
			<%= select_tag "board_id", options_for_select(@boards.collect{ |b| [b.name, b.id] }) %>
    		<%= f.submit %>
	<% end %>
</div>

app/views/boards/_form.html.erb
<%= form_for ([current_user, board]) do |f| %>
  <% if board.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(board.errors.count, "error") %> prohibited this image from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>  
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  
  <br/><br />
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= link_to 'Back', user_boards_path %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/boards/_new_board.html.erb
<div class="modal hide fade" id="createBoard" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create Board</h4>
      </div>
      <div class="modal-body">
        <p>
          <h5>Create Board</h5>
          <%= form_for(board) do |f| %>
          <% if board.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

              <ul>
              <% board.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          
          <div class="field">
            <%= f.hidden_field :user_id %>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/boards/board_selection.html.erb
<div class = "board_selection_container">
	<%= form_for(@category, :url => update_boards_user_boards_path(current_user.id, @board), :html => { :method => :post } ) do |f| %>
			<%= select_tag "board_id", options_for_select(@boards.collect{ |b| [b.name, b.id] }) %>
    		<%= f.submit %>
	<% end %>
</div>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', user_board_path(current_user.id, @board)%> |
<%= link_to 'Back', user_boards_path %>

app/views/boards/index.html.erb
<h1 class="page-header">Boards</h1>

<% @boards.each do |board| %>
  <div class="jumbotron">
      <div class = "container">
        <h3 align="center">
          <%= link_to board.name, user_board_path(current_user.id, board.id) %>
        </h3>
      </div>
  </div>
<% end %>


<%= link_to 'New Board', new_user_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

app/views/boards/new_board.js.erb
$("#createBoard").html("<%= escape_javascript(render 'users/new_board') %>");
$('#createBoard').modal('show');

app/views/boards/show.html.erb
<%= link_to 'Edit', edit_user_board_path(@board) %> |
<%= link_to 'Back', user_boards_path %>

<h1 class="page-header" align="center"><%= @board.name %><h5 align="right"><small>Board is associated with : <%= @board.user.email %></small><h5></h1>
<br />
<% count = 0 %>
<% @board.images.each do |image| %>
  <% if count % 3 == 0 %>
    <div class="row">
   <% end %>
   <% count += 1 %> 
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src= <%= image.src %> />
        <div class="caption">
          <% if image.tags.exists? %>
            <h3>Tags</h3>
              <% image.tags.each do |p| %>
                <span class="label label-info"><%= p.tag %></span>
              <% end %>
          <% end %>
          <br /><br />
        </div>
      </div>
    </div>
  <% if count % 3 == 0  %>
    </div>
  <% end %> 
<% end %> 