config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  resources :images
  
  resources :users do 
  	resources :boards do
  		collection do
  			get :board_selection
  			
  		end
  	end
  end
  post '/boards/update_boards'
  root to: "images#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord
	has_many :tags, inverse_of: :image
	accepts_nested_attributes_for :tags

	validates :src, uniqueness: true
	validates :src, presence: true
	
	has_many :categories
	has_many :boards, through: :categories
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    #checking if the search box is returning any value
    @images = []
    if params[:search]
      #if it does then fetch tags
      tags = Tag.where(tag: params[:search])
      if !tags.empty?
        #if tags are present then there will be some images related to those tags
        if tags.size > 1
          tags.each do |tag|
            #storing them in an instance var
            @images = @images + Image.where(id: tag.image_id)
          end
        end
      else
        #if searched tag is not present in db
        @images = Image.all  
      end
    else
      #for empty field
      @images = Image.all    
    end

  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
    @image.tags.build
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:src, tags_attributes: [:id, :tag ])
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image , :html => { :class => "form-horizontal event" }  do |f| %>
  <% if image.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>  
    </div>
  <% end %>

  
  <div class="form-group">
    <%= f.label :src, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :src, :class => 'form-control' %>
    </div>
  </div>

  <%= f.fields_for :tags do |builder| %>
    <%= render 'tag_fields', f: builder %>
  <% end %>

  <%= link_to_add_tag "Add Tag", f, :tags %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/images/_subcategory_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Select Board</h4>
      </div>
      <% if current_user.present? %>    
        <div class="modal-body">
        <% b = current_user.boards %>
        <% if b.present? %>
          <%= hidden_field_tag 'image', id: "", class: "image_id" %>
          <%= select_tag "board_id", options_for_select(b.collect{ |b| [b.name, b.id] }) %>
          <%= submit_tag 'Select', id: 'submit-btn' %>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/images/_tag_fields.html.erb
<fieldset>
	<div class="form-group">
		<%= f.label :tag, "Tag", :class => 'control-label col-lg-2' %><br />
		<div class="col-lg-4">
			<%= f.text_field :tag, :class => 'form-control' %>
		</div>
	</div>	
</fieldset>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<!--
<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>
-->

app/views/images/index.html.erb
<%= form_tag images_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<h1 class="page-header">Images</h1>
<br>
<% @images.each do |image| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src= <%= image.src %> />
        <div class="caption">
          <% if image.tags.exists? %>
            <h3>Tags</h3>
              <% image.tags.each do |p| %>
                <span class="label label-info"><%= p.tag %></span>
              <% end %>
          <% end %>
          <br /><br />
          <p>
          <% if user_signed_in? %>
          <a href="#" class="btn btn-danger pin-btn" id = '<%= image.id %>' data-toggle="modal" data-target="#myModal">Pin</a>
          <% end %>
          </p>
        </div>
      </div>
    </div>
<% end %>

<%= render partial: 'subcategory_modal' %>
<script>
  var image_id = ""
  
  $('.pin-btn').click(function(e){
    e.preventDefault();
    image_id = $('.image_id').attr('id');
    $('#myModal').show();
  });

  $('#submit-btn').click(function(e){
    e.preventDefault();
    values = {}
    values['board_id'] = $('#board_id option:selected').val();
    values['image_id'] = image_id
    console.log(values);
    $.ajax({
      type:'POST', 
      url: '/boards/update_boards', 
      data: values
    }).done(function(response){
      console.log(values);
      if(response.message == "already")
        alert("Already available in this board");
      $('#myModal').modal('hide');  
    });
  });
</script>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p>
  <%= link_to 'Edit', edit_image_path(@image) %> |
  <%= link_to 'Back', images_path %>
</p>
<div class="col-sm-6 col-md-4">
      <div class="thumbnail">
      	<img src= <%= @image.src %> />
       		<div class="caption">
          		<% if @image.tags.exists? %>
            	<h3>Tags</h3>
              	<% @image.tags.each do |p| %>
                <span class="label label-info"><%= p.tag %></span>
              	<% end %>
          		<% end %>
          
      		</div>
   		</div>
</div>